# Generated by Django 5.0 on 2024-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualA', '0002_services_delete_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Accessing_id',
            new_name='Access_id',
        ),
    ]
